name = "baldanders-info"
license = "CC-BY"
licenselink = "https://github.com/spiegel-im-spiegel/hugo-theme-baldanders-info/blob/master/LICENSE"
description = "Hugo Theme for Baldanders.info"
homepage = "https://baldanders.info/"
tags = ["blog", "text", "photo"]
features = ["text", "photo", "cc-license", "social"]
min_version = 0.54

[author]
  name = "Spiegel"
  homepage = "https://baldanders.info/"
