# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Text"
license = "CC0-1.0"
licenselink = "https://github.com/spiegel-im-spiegel/hugo-theme-text/blob/master/LICENSE"
description = "Simple Text (Hugo Theme)"
homepage = "http://text.baldanders.info/"
tags = ["text", "blog"]
features = ["blog", "theme"]
min_version = 0.14

[author]
  name = "Spiegel"
  homepage = "http://www.baldanders.info/"
